@startuml
abstract class Empleado {
  -string nombre
  -double salario
  -int fechaContratacion
  +{abstract} double calcularSalario() ;
  +{abstract} void mostrarDatos() ;
  +{abstract} void ingresarDatos() ;
  +{abstract} string serializar()  ;
  +{abstract} void deserializar(string data) ;
}

class Gerente {
  -string nombre
  -double salario
  -int fechaContratacion
  -double bono
  -string departamento

  +double calcularSalario() ;
  +void mostrarDatos() ;
  +void ingresarDatos() ;
  +string serializar()  ;
  +void deserializar(string data) ;
}

class Desarrollador {
  -string nombre
  -double salario
  -int fechaContratacion
  -int horasExtras
  -string lenguaje
  -string programa;
  -int proyectos;

  +double calcularSalario() ;
  +void mostrarDatos() ;
  +void ingresarDatos() ;
  +string serializar()  ;
  +void deserializar(string data) ;
}

class Disenador {
  -string nombre
  -double salario
  -int fechaContratacion
  -string programa;
  -int proyectos;

  +double calcularSalario() ;
  +void mostrarDatos() ;
  +void ingresarDatos() ;
  +string serializar()  ;
  +void deserializar(string data) ;
}

class Tester {
  -string nombre
  -double salario
  -int fechaContratacion
  -int bugs;
  -string system;

  +double calcularSalario() ;
  +void mostrarDatos() ;
  +void ingresarDatos() ;
  +string serializar()  ;
  +void deserializar(string data) ;
}

Empleado <|-- Gerente
Empleado <|-- Desarrollador
Empleado <|-- Disenador
Empleado <|-- Tester

class GestorArchivos {
  +static void guardar(string& archivo, const vector<Empleado*>& empleados)
  +static void cargar(string& archivo, vector<Empleado*>& empleados)
}

class Departamento {
  -vector<Empleado*> empleados
  -GestorArchivos manejadorArchivos
  +void agregarEmpleado(Empleado* empleado)
  +void eliminarEmpleado(const string& nombre)
  +void editarEmpleado(const string& nombre, const string& nuevoNombre, double nuevoSalario, int nuevaFechaContratacion)
  +Empleado* buscarEmpleado(const string& nombre)
  +void listarEmpleados()
  +void guardar(const string& archivo)
  +void cargar(const string& archivo)
}

Departamento *-- GestorArchivos : composición
Departamento *-- Empleado : composición
@enduml