@startuml
actor main
main -> Empleados: new Gerente("Juan", 1000, 2020, "Sistemas", 500)
activate Empleados
Empleados --> main
deactivate Empleados

main -> Empleados: new Desarrollador("Pedro", 800, 2021, "Java", 10)
activate Empleados
Empleados --> main
deactivate Empleados

main -> Empleados: new Diseñador("Maria", 700, 2022, "Web", 5)
activate Empleados
Empleados --> main
deactivate Empleados

main -> Empleados: new Tester("Luis", 600, 2023, "Manual", 20)
activate Empleados
Empleados --> main
deactivate Empleados

main -> Empleados: calcularSalario()
activate Empleados
Empleados --> main
deactivate Empleados
@enduml